import { StyleSheet } from 'react-native';

const EditUserStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: '#f9f9f9',
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 25,
    color: '#16A085',
  },
  input: {
    flex: 1,
    padding: 14,
    fontSize: 16,
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderWidth: 0,                 
    marginBottom: 10,
    elevation: 0,                  
    shadowColor: 'transparent',    
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 10,
    color: '#444',
    textAlign: 'left',
  },  
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bbb',
    paddingHorizontal: 10,
    marginBottom: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  addButton: {
    width: 42,
    height: 42,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  listItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 14,
    borderRadius: 12,
    marginBottom: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  listItem: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  deleteIcon: {
    padding: 6,
  },
  expenseButton: {
    backgroundColor: '#e74c3c',
  },
  incomeButton: {
    backgroundColor: '#2ecc71',
  },
  expenseSection: {
    borderLeftWidth: 5,
    borderLeftColor: '#e74c3c',
    paddingLeft: 10,
    paddingVertical: 10,
    marginBottom: 20,
  },
  incomeSection: {
    borderLeftWidth: 5,
    borderLeftColor: '#2ecc71',
    paddingLeft: 10,
    paddingVertical: 10,
    marginBottom: 20,
  },
  button: {
    backgroundColor: '#16A085',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  loadingIndicator: {
    marginTop: 10,
  },
});

export default EditUserStyles;
