import { StyleSheet, Platform } from 'react-native';

const LoginStyles = StyleSheet.create({
  container: {
    padding: 20,
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#f7f7f7',
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 20,
  },
  logo: {
    width: 130,
    height: 130,
    alignSelf: 'center',
    marginBottom: 20,
    marginTop: 30,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    // marginBottom: 10,
    fontFamily: 'Roboto',
  },
  subHeader: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom: 5,
    fontFamily: 'Roboto',
  },
  input: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    marginBottom: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    height: 50,
    width: '100%',
  },
  passwordContainer: {
    position: 'relative',
    width: '100%',
  },
  inputPassword: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    height: 50,
    width: '100%',
    paddingRight: 40,
  },
  eyeIconContainer: {
    position: 'absolute',
    right: 12,
    top: '50%',
    transform: [{ translateY: -12 }],
  },
  iconContainer: {
    position: 'absolute',
    right: 12,
    top: '50%',
    transform: [{ translateY: -12 }],
  },
  footer: {
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    fontSize: 14,
    color: '#BDC3C7',
    marginBottom: 8,
    fontFamily: 'Roboto',
  },
  formError: {
    color: '#E74C3C',
    marginTop: 5,
    fontSize: 14,
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#3498DB',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 15,
    elevation: 4,
  },
  buttonSmall: {
    backgroundColor: '#2ECC71',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 8,
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto',
  },
  link: {
    color: '#3498DB',
    fontSize: 14,
    marginTop: 12,
    textDecorationLine: 'underline',
    fontFamily: 'Roboto',
  },
  banner: {
    padding: 12,
    marginBottom: 15,
    width: '100%',
    textAlign: 'center',
    borderRadius: 8,
  },
  successBanner: {
    backgroundColor: '#2ECC71',
  },
  errorBanner: {
    backgroundColor: '#E74C3C',
  },
  bannerText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  successBorder: {
    borderColor: '#2ECC71',
    borderWidth: 2,
    borderRadius: 8,
  },
  errorBorder: {
    borderColor: '#E74C3C',
    borderWidth: 2,
    borderRadius: 8,
  },
  successText: {
    color: '#2ECC71',
    fontSize: 14,
    marginTop: 5,
    textAlign: 'center',
  },
  // Miglioramento grafico della gestione preferenze
  listContainer: {
    marginVertical: 10,
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  listItem: {
    fontSize: 16,
    color: '#2C3E50',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  removeButton: {
    backgroundColor: '#E74C3C',
    padding: 8,
    borderRadius: 8,
    marginLeft: 10,
    elevation: 2,
  },
  removeButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  addButton: {
    backgroundColor: '#3498DB',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 15,
    elevation: 3,
  },
  addButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  defaultPreference: {
    opacity: 0.6, // Per indicare che non può essere rimossa
  },
  inputContainer: {
    marginBottom: 15,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  sectionContainer: {
    marginVertical: 10,
    // padding: 15,
    // backgroundColor: '#ecf0f1',
    borderRadius: 10,
  },
  listItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 15,
    backgroundColor: '#fff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
    marginBottom: 10,
  },
});

export default LoginStyles;
