import { StyleSheet, Platform } from 'react-native';

const LoginStyles = StyleSheet.create({
  container: {
    width: '90%',
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'center',
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20
  },
  logo: {
    width: 130,
    height: 130,
    alignSelf: 'center',
    marginBottom: 20,
    marginTop: 30,
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  subHeader: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom: 5,
    fontFamily: 'Roboto',
  },
  input: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    marginBottom: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    height: 50,
    color: '#000000',
    width: '100%',
  },
  inputPassword: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    paddingHorizontal: 15,
    paddingVertical: 12,
    color: '#000000',
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    height: 50,
    width: '100%',
    paddingRight: 40,
  },
  eyeIconContainer: {
    position: 'absolute',
    right: 12,
    top: '50%',
    transform: [{ translateY: -12 }],
  },
  iconContainer: {
    position: 'absolute',
    right: 12,
    top: '50%',
    transform: [{ translateY: -12 }],
  },
  footer: {
    marginTop: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerText: {
    fontSize: 14,
    color: '#BDC3C7',
    marginBottom: 8,
    fontFamily: 'Roboto',
  },
  formError: {
    color: '#E74C3C',
    marginTop: 5,
    fontSize: 14,
    textAlign: 'center',
  },
  link: {
    color: '#3498DB',
    fontSize: 14,
    marginTop: 12,
    textDecorationLine: 'underline',
    fontFamily: 'Roboto',
  },
  banner: {
    padding: 12,
    marginBottom: 15,
    width: '100%',
    textAlign: 'center',
    borderRadius: 8,
  },
  bannerText: {
    color: '#2ECC71',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
});

export default LoginStyles;
