import { StyleSheet, Platform } from 'react-native';

const ResetForgotPwd = StyleSheet.create({
  container: {
    width: '90%',
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'center',
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
  },
  header: {
    fontSize: 28,
    paddingBottom: 15,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  subHeader: {
    fontSize: 14,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom: 5,
    fontFamily: 'Roboto',
  },
  input: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    marginBottom: 15,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    height: 50,
    width: '100%',
  },
  inputPassword: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    height: 50,
    width: '100%',
    paddingRight: 40,
  },
  button: {
    backgroundColor: '#3498DB',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 15,
    elevation: 4,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'Roboto',
  },
  link: {
    color: '#3498DB',
    fontSize: 14,
    marginTop: 12,
    textDecorationLine: 'underline',
    fontFamily: 'Roboto',
  },
});

export default ResetForgotPwd;
