name: Create APK

on:
  push:
    tags:
      - '*'

env:
  EAS_PROFILE: preview

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build Android APK with profile ${{ env.EAS_PROFILE }}
        run: eas build --platform android --profile $EAS_PROFILE --non-interactive
